/**
 * Debi codegen — generates Server.luau / Client.luau
 *
 * Binding rules (security / style):
 * - `const` for immutable bindings: services, requires, numeric limits, helpers, Debi table
 * - `local` only for mutable state (queues, writers, remotes, callbacks, counters)
 * - Prefer `const function` for stable helpers (serialize/dispatch/flush)
 * - No `@native` by default — only add after measured hot-path need
 */

const path = require("path");
const {
  luauType,
  writeExpr,
  readExpr,
  readArrayBlock,
} = require("./packTypes");

function buildTypeMap(types) {
  const map = {};
  for (const [name, def] of Object.entries(types)) {
    if (def.kind === "struct") {
      map[name] = { kind: "struct", fields: def.fields };
    } else if (def.kind === "alias") {
      map[name] = def.type;
    }
  }
  return map;
}

function genStructHelpers(typeMap) {
  const lines = [];
  for (const [name, def] of Object.entries(typeMap)) {
    if (def.kind !== "struct") continue;

    lines.push(`export type ${name} = {`);
    for (const field of def.fields) {
      lines.push(`\t${field.name}: ${luauType(field.type, typeMap)},`);
    }
    lines.push(`}`);
    lines.push(``);

    lines.push(`const function write${name}(w: BufferWriter.BufferWriter, value: ${name})`);
    for (const field of def.fields) {
      const expr = writeExpr("w", `value.${field.name}`, field.type, typeMap);
      for (const line of expr.split("\n")) {
        lines.push(`\t${line}`);
      }
    }
    lines.push(`end`);
    lines.push(``);

    lines.push(`const function read${name}(r: BufferReader.BufferReader): ${name}`);
    lines.push(`\tconst value: ${name} = {} :: any`);
    for (const field of def.fields) {
      if (field.type.kind === "array") {
        lines.push(readArrayBlock("r", `__${field.name}`, field.type, typeMap, "\t"));
        lines.push(`\tvalue.${field.name} = __${field.name}`);
      } else {
        const rd = readExpr("r", field.type, typeMap);
        lines.push(`\tvalue.${field.name} = ${rd}`);
      }
    }
    lines.push(`\treturn value`);
    lines.push(`end`);
    lines.push(``);
  }
  return lines.join("\n");
}

function eventArgsLuau(event, typeMap, withPlayer) {
  const parts = [];
  if (withPlayer) parts.push("player: Player");
  for (const field of event.data) {
    parts.push(`${field.name}: ${luauType(field.type, typeMap)}`);
  }
  return parts.join(", ");
}

function writeEventPayload(event, typeMap, indent = "\t") {
  const lines = [];
  for (const field of event.data) {
    if (field.type.kind === "array") {
      lines.push(
        `${indent}do`,
        `${indent}\tconst __arr = ${field.name}`,
        `${indent}\tw:writeu16(#__arr)`,
        `${indent}\tfor __, __item in __arr do`
      );
      const inner = writeExpr("w", "__item", field.type.element, typeMap);
      for (const line of inner.split("\n")) {
        lines.push(`${indent}\t\t${line}`);
      }
      lines.push(`${indent}\tend`, `${indent}end`);
    } else {
      const expr = writeExpr("w", field.name, field.type, typeMap);
      for (const line of expr.split("\n")) {
        lines.push(`${indent}${line}`);
      }
    }
  }
  return lines.join("\n");
}

function readEventPayload(event, typeMap, indent = "\t") {
  const lines = [];
  const names = [];
  for (const field of event.data) {
    names.push(field.name);
    if (field.type.kind === "array") {
      lines.push(readArrayBlock("r", field.name, field.type, typeMap, indent));
    } else {
      const rd = readExpr("r", field.type, typeMap);
      lines.push(`${indent}const ${field.name} = ${rd}`);
    }
  }
  return { lines: lines.join("\n"), names };
}

function generateServer(ast, runtimeRequirePath, channelName) {
  const typeMap = buildTypeMap(ast.types);
  const events = ast.events;
  const channel = channelName || ast.opts.channel || "Game";
  const lines = [];

  lines.push(`--!strict`);
  lines.push(`-- AUTO-GENERATED by Debi (${channel}). Do not edit.`);
  lines.push(``);
  lines.push(`const RunService = game:GetService("RunService")`);
  lines.push(`const ReplicatedStorage = game:GetService("ReplicatedStorage")`);
  lines.push(`const Players = game:GetService("Players")`);
  lines.push(``);
  lines.push(`const BufferWriter = require(${runtimeRequirePath}.BufferWriter)`);
  lines.push(`const BufferReader = require(${runtimeRequirePath}.BufferReader)`);
  lines.push(`const Remotes = require(${runtimeRequirePath}.Remotes)`);
  lines.push(``);
  lines.push(`const CHANNEL = "${channel}"`);
  lines.push(`const MAX_RELIABLE_BYTES = 8192`);
  lines.push(`const MAX_UNRELIABLE_BYTES = 900`);
  lines.push(`const MAX_EVENTS_PER_PACKET = 64`);
  lines.push(`const RATE_LIMIT_WINDOW = 1`);
  lines.push(`const RATE_LIMIT_MAX = 90`);
  lines.push(``);
  lines.push(`assert(RunService:IsServer(), "[Debi/${channel}] Server.luau can only be required on the server")`);
  lines.push(``);
  lines.push(genStructHelpers(typeMap));

  // Mutable runtime state
  lines.push(`local reliableWriter = BufferWriter.new()`);
  lines.push(`local unreliableWriter = BufferWriter.new()`);
  lines.push(`local reliableQueues: { [Player]: BufferWriter.BufferWriter } = {}`);
  lines.push(`local unreliableQueues: { [Player]: BufferWriter.BufferWriter } = {}`);
  lines.push(`local remotes: Remotes.DebiRemotes? = nil`);
  lines.push(`local flushing = false`);
  lines.push(`local packetCounts: { [Player]: { count: number, resetAt: number } } = {}`);
  lines.push(``);

  for (const event of events) {
    if (event.from !== "Client") continue;
    const args = eventArgsLuau(event, typeMap, true);
    if (event.call.startsWith("Many")) {
      lines.push(`local ${event.name}_callbacks: { (${args}) -> () } = {}`);
    } else {
      lines.push(`local ${event.name}_callback: ((${args}) -> ())? = nil`);
    }
  }
  lines.push(``);

  lines.push(`const function getQueue(map: { [Player]: BufferWriter.BufferWriter }, player: Player): BufferWriter.BufferWriter`);
  lines.push(`\tlocal q = map[player]`);
  lines.push(`\tif not q then`);
  lines.push(`\t\tq = BufferWriter.new()`);
  lines.push(`\t\tmap[player] = q`);
  lines.push(`\tend`);
  lines.push(`\treturn q`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const function flushPlayer(player: Player, map: { [Player]: BufferWriter.BufferWriter }, remote: RemoteEvent | UnreliableRemoteEvent)`);
  lines.push(`\tconst q = map[player]`);
  lines.push(`\tif not q or q:len() == 0 then`);
  lines.push(`\t\treturn`);
  lines.push(`\tend`);
  lines.push(`\tremote:FireClient(player, q:toBuffer())`);
  lines.push(`\tq:reset()`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const function flushAll()`);
  lines.push(`\tconst r = remotes`);
  lines.push(`\tif not r then`);
  lines.push(`\t\treturn`);
  lines.push(`\tend`);
  lines.push(`\tfor player in reliableQueues do`);
  lines.push(`\t\tflushPlayer(player, reliableQueues, r.Reliable)`);
  lines.push(`\tend`);
  lines.push(`\tfor player in unreliableQueues do`);
  lines.push(`\t\tflushPlayer(player, unreliableQueues, r.Unreliable)`);
  lines.push(`\tend`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const function allowPacket(player: Player): boolean`);
  lines.push(`\tconst now = os.clock()`);
  lines.push(`\tconst entry = packetCounts[player]`);
  lines.push(`\tif not entry or now >= entry.resetAt then`);
  lines.push(`\t\tpacketCounts[player] = { count = 1, resetAt = now + RATE_LIMIT_WINDOW }`);
  lines.push(`\t\treturn true`);
  lines.push(`\tend`);
  lines.push(`\tif entry.count >= RATE_LIMIT_MAX then`);
  lines.push(`\t\treturn false`);
  lines.push(`\tend`);
  lines.push(`\tentry.count += 1`);
  lines.push(`\treturn true`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const function dispatchClient(player: Player, buf: buffer)`);
  lines.push(`\tpcall(function()`);
  lines.push(`\t\tconst r = BufferReader.new(buf)`);
  lines.push(`\t\tlocal eventsRead = 0`);
  lines.push(`\t\twhile r:hasMore() do`);
  lines.push(`\t\t\teventsRead += 1`);
  lines.push(`\t\t\tif eventsRead > MAX_EVENTS_PER_PACKET then`);
  lines.push(`\t\t\t\treturn`);
  lines.push(`\t\t\tend`);
  lines.push(`\t\t\tconst id = r:readu8()`);

  let hasClientEvent = false;
  for (let i = 0; i < events.length; i++) {
    const event = events[i];
    if (event.from !== "Client") continue;
    hasClientEvent = true;
    const id = i + 1;
    const { lines: readLines, names } = readEventPayload(event, typeMap, "\t\t\t\t");
    lines.push(`\t\t\tif id == ${id} then`);
    lines.push(readLines);
    if (event.call.startsWith("Many")) {
      lines.push(`\t\t\t\tfor _, cb in ${event.name}_callbacks do`);
      lines.push(`\t\t\t\t\ttask.spawn(cb, player${names.length ? ", " + names.join(", ") : ""})`);
      lines.push(`\t\t\t\tend`);
    } else {
      lines.push(`\t\t\t\tconst cb = ${event.name}_callback`);
      lines.push(`\t\t\t\tif cb then`);
      if (event.call.includes("Sync")) {
        lines.push(`\t\t\t\t\tcb(player${names.length ? ", " + names.join(", ") : ""})`);
      } else {
        lines.push(`\t\t\t\t\ttask.spawn(cb, player${names.length ? ", " + names.join(", ") : ""})`);
      }
      lines.push(`\t\t\t\tend`);
    }
    lines.push(`\t\t\t\tcontinue`);
    lines.push(`\t\t\tend`);
  }
  if (!hasClientEvent) {
    lines.push(`\t\t\treturn`);
  } else {
    lines.push(`\t\t\t-- unknown / Server-only ids: drop silently`);
    lines.push(`\t\t\treturn`);
  }
  lines.push(`\t\tend`);
  lines.push(`\tend)`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const function handleIncoming(player: Player, payload: unknown, maxBytes: number)`);
  lines.push(`\tif typeof(payload) ~= "buffer" then`);
  lines.push(`\t\treturn`);
  lines.push(`\tend`);
  lines.push(`\tconst buf = payload :: buffer`);
  lines.push(`\tif buffer.len(buf) <= 0 or buffer.len(buf) > maxBytes then`);
  lines.push(`\t\treturn`);
  lines.push(`\tend`);
  lines.push(`\tif not allowPacket(player) then`);
  lines.push(`\t\treturn`);
  lines.push(`\tend`);
  lines.push(`\tdispatchClient(player, buf)`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const Debi = {}`);
  lines.push(``);

  for (let i = 0; i < events.length; i++) {
    const event = events[i];
    const id = i + 1;
    if (event.from !== "Server") continue;

    const argsSig = eventArgsLuau(event, typeMap, false);
    const queueMap = event.reliability === "Unreliable" ? "unreliableQueues" : "reliableQueues";

    lines.push(`Debi.${event.name} = {}`);
    lines.push(``);
    lines.push(`function Debi.${event.name}.Fire(player: Player${argsSig ? ", " + argsSig : ""})`);
    lines.push(`\tconst w = getQueue(${queueMap}, player)`);
    lines.push(`\tw:writeu8(${id})`);
    if (event.data.length) {
      lines.push(writeEventPayload(event, typeMap, "\t"));
    }
    lines.push(`end`);
    lines.push(``);
    lines.push(`function Debi.${event.name}.FireAll(${argsSig})`);
    lines.push(`\tfor _, player in Players:GetPlayers() do`);
    lines.push(`\t\tDebi.${event.name}.Fire(player${event.data.map((f) => ", " + f.name).join("")})`);
    lines.push(`\tend`);
    lines.push(`end`);
    lines.push(``);
    lines.push(`function Debi.${event.name}.FireExcept(except: Player${argsSig ? ", " + argsSig : ""})`);
    lines.push(`\tfor _, player in Players:GetPlayers() do`);
    lines.push(`\t\tif player ~= except then`);
    lines.push(`\t\t\tDebi.${event.name}.Fire(player${event.data.map((f) => ", " + f.name).join("")})`);
    lines.push(`\t\tend`);
    lines.push(`\tend`);
    lines.push(`end`);
    lines.push(``);
  }

  for (const event of events) {
    if (event.from !== "Client") continue;
    const args = eventArgsLuau(event, typeMap, true);
    lines.push(`Debi.${event.name} = Debi.${event.name} or {}`);
    if (event.call.startsWith("Many")) {
      lines.push(`function Debi.${event.name}.On(cb: (${args}) -> ())`);
      lines.push(`\ttable.insert(${event.name}_callbacks, cb)`);
      lines.push(`end`);
    } else {
      lines.push(`function Debi.${event.name}.SetCallback(cb: (${args}) -> ())`);
      lines.push(`\t${event.name}_callback = cb`);
      lines.push(`end`);
    }
    lines.push(``);
  }

  lines.push(`function Debi.Flush()`);
  lines.push(`\tflushAll()`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`do`);
  lines.push(`\tconst r = Remotes.getServer(CHANNEL)`);
  lines.push(`\tremotes = r`);
  lines.push(`\tPlayers.PlayerRemoving:Connect(function(player: Player)`);
  lines.push(`\t\tpacketCounts[player] = nil`);
  lines.push(`\t\treliableQueues[player] = nil`);
  lines.push(`\t\tunreliableQueues[player] = nil`);
  lines.push(`\tend)`);
  lines.push(`\tr.Reliable.OnServerEvent:Connect(function(player: Player, payload: unknown)`);
  lines.push(`\t\thandleIncoming(player, payload, MAX_RELIABLE_BYTES)`);
  lines.push(`\tend)`);
  lines.push(`\tr.Unreliable.OnServerEvent:Connect(function(player: Player, payload: unknown)`);
  lines.push(`\t\thandleIncoming(player, payload, MAX_UNRELIABLE_BYTES)`);
  lines.push(`\tend)`);
  lines.push(`\tRunService.Heartbeat:Connect(function()`);
  lines.push(`\t\tif flushing then`);
  lines.push(`\t\t\treturn`);
  lines.push(`\t\tend`);
  lines.push(`\t\tflushing = true`);
  lines.push(`\t\tflushAll()`);
  lines.push(`\t\tflushing = false`);
  lines.push(`\tend)`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`return Debi`);
  lines.push(``);
  return lines.join("\n");
}

function generateClient(ast, runtimeRequirePath, channelName) {
  const typeMap = buildTypeMap(ast.types);
  const events = ast.events;
  const channel = channelName || ast.opts.channel || "Game";
  const lines = [];

  lines.push(`--!strict`);
  lines.push(`-- AUTO-GENERATED by Debi (${channel}). Do not edit.`);
  lines.push(``);
  lines.push(`const RunService = game:GetService("RunService")`);
  lines.push(`const ReplicatedStorage = game:GetService("ReplicatedStorage")`);
  lines.push(`const Players = game:GetService("Players")`);
  lines.push(``);
  lines.push(`const BufferWriter = require(${runtimeRequirePath}.BufferWriter)`);
  lines.push(`const BufferReader = require(${runtimeRequirePath}.BufferReader)`);
  lines.push(`const Remotes = require(${runtimeRequirePath}.Remotes)`);
  lines.push(``);
  lines.push(`const CHANNEL = "${channel}"`);
  lines.push(``);
  lines.push(`assert(RunService:IsClient(), "[Debi/${channel}] Client.luau can only be required on the client")`);
  lines.push(``);
  lines.push(genStructHelpers(typeMap));

  lines.push(`local reliableWriter = BufferWriter.new()`);
  lines.push(`local unreliableWriter = BufferWriter.new()`);
  lines.push(`local remotes: Remotes.DebiRemotes? = nil`);
  lines.push(`local flushing = false`);
  lines.push(``);

  for (const event of events) {
    if (event.from !== "Server") continue;
    const args = eventArgsLuau(event, typeMap, false);
    if (event.call.startsWith("Many")) {
      lines.push(`local ${event.name}_callbacks: { (${args}) -> () } = {}`);
    } else {
      lines.push(`local ${event.name}_callback: ((${args}) -> ())? = nil`);
    }
  }
  lines.push(``);

  lines.push(`const function flushWriter(w: BufferWriter.BufferWriter, remote: RemoteEvent | UnreliableRemoteEvent)`);
  lines.push(`\tif w:len() == 0 then`);
  lines.push(`\t\treturn`);
  lines.push(`\tend`);
  lines.push(`\tremote:FireServer(w:toBuffer())`);
  lines.push(`\tw:reset()`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const function flushAll()`);
  lines.push(`\tconst r = remotes`);
  lines.push(`\tif not r then`);
  lines.push(`\t\treturn`);
  lines.push(`\tend`);
  lines.push(`\tflushWriter(reliableWriter, r.Reliable)`);
  lines.push(`\tflushWriter(unreliableWriter, r.Unreliable)`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const function dispatchServer(buf: buffer)`);
  lines.push(`\tconst r = BufferReader.new(buf)`);
  lines.push(`\twhile r:hasMore() do`);
  lines.push(`\t\tconst id = r:readu8()`);

  for (let i = 0; i < events.length; i++) {
    const event = events[i];
    if (event.from !== "Server") continue;
    const id = i + 1;
    const { lines: readLines, names } = readEventPayload(event, typeMap, "\t\t\t");
    lines.push(`\t\tif id == ${id} then`);
    lines.push(readLines);
    if (event.call.startsWith("Many")) {
      lines.push(`\t\t\tfor _, cb in ${event.name}_callbacks do`);
      lines.push(`\t\t\t\ttask.spawn(cb${names.length ? ", " + names.join(", ") : ""})`);
      lines.push(`\t\t\tend`);
    } else {
      lines.push(`\t\t\tconst cb = ${event.name}_callback`);
      lines.push(`\t\t\tif cb then`);
      if (event.call.includes("Sync")) {
        lines.push(`\t\t\t\tcb(${names.join(", ")})`);
      } else {
        lines.push(`\t\t\t\ttask.spawn(cb${names.length ? ", " + names.join(", ") : ""})`);
      }
      lines.push(`\t\t\tend`);
    }
    lines.push(`\t\t\tcontinue`);
    lines.push(`\t\tend`);
  }
  lines.push(`\t\twarn("[Debi] unknown server event id", id)`);
  lines.push(`\tend`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`const Debi = {}`);
  lines.push(``);

  for (let i = 0; i < events.length; i++) {
    const event = events[i];
    const id = i + 1;
    if (event.from !== "Client") continue;
    const argsSig = eventArgsLuau(event, typeMap, false);
    const writer = event.reliability === "Unreliable" ? "unreliableWriter" : "reliableWriter";

    lines.push(`Debi.${event.name} = {}`);
    lines.push(``);
    lines.push(`function Debi.${event.name}.Fire(${argsSig})`);
    lines.push(`\tconst w = ${writer}`);
    lines.push(`\tw:writeu8(${id})`);
    if (event.data.length) {
      lines.push(writeEventPayload(event, typeMap, "\t"));
    }
    lines.push(`end`);
    lines.push(``);
  }

  for (const event of events) {
    if (event.from !== "Server") continue;
    const args = eventArgsLuau(event, typeMap, false);
    lines.push(`Debi.${event.name} = Debi.${event.name} or {}`);
    if (event.call.startsWith("Many")) {
      lines.push(`function Debi.${event.name}.On(cb: (${args}) -> ())`);
      lines.push(`\ttable.insert(${event.name}_callbacks, cb)`);
      lines.push(`end`);
    } else {
      lines.push(`function Debi.${event.name}.SetCallback(cb: (${args}) -> ())`);
      lines.push(`\t${event.name}_callback = cb`);
      lines.push(`end`);
    }
    lines.push(``);
  }

  lines.push(`function Debi.Flush()`);
  lines.push(`\tflushAll()`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`do`);
  lines.push(`\tconst r = Remotes.getClient(CHANNEL)`);
  lines.push(`\tremotes = r`);
  lines.push(`\tr.Reliable.OnClientEvent:Connect(function(payload: unknown)`);
  lines.push(`\t\tif typeof(payload) ~= "buffer" then`);
  lines.push(`\t\t\treturn`);
  lines.push(`\t\tend`);
  lines.push(`\t\tdispatchServer(payload :: buffer)`);
  lines.push(`\tend)`);
  lines.push(`\tr.Unreliable.OnClientEvent:Connect(function(payload: unknown)`);
  lines.push(`\t\tif typeof(payload) ~= "buffer" then`);
  lines.push(`\t\t\treturn`);
  lines.push(`\t\tend`);
  lines.push(`\t\tdispatchServer(payload :: buffer)`);
  lines.push(`\tend)`);
  lines.push(`\tRunService.Heartbeat:Connect(function()`);
  lines.push(`\t\tif flushing then`);
  lines.push(`\t\t\treturn`);
  lines.push(`\t\tend`);
  lines.push(`\t\tflushing = true`);
  lines.push(`\t\tflushAll()`);
  lines.push(`\t\tflushing = false`);
  lines.push(`\tend)`);
  lines.push(`end`);
  lines.push(``);

  lines.push(`return Debi`);
  lines.push(``);
  return lines.join("\n");
}

function generate(ast, { configDir, channelName }) {
  const channel = channelName || ast.opts.channel || "Game";
  const serverRel = ast.opts.server_output || `src/Networker/${channel}/Server.luau`;
  const clientRel = ast.opts.client_output || `src/Networker/${channel}/Client.luau`;

  const runtimeRequirePath = `ReplicatedStorage.Shareds.Modules.Debi`;

  return {
    serverPath: path.isAbsolute(serverRel) ? serverRel : path.join(configDir, serverRel),
    clientPath: path.isAbsolute(clientRel) ? clientRel : path.join(configDir, clientRel),
    serverSource: generateServer(ast, runtimeRequirePath, channel),
    clientSource: generateClient(ast, runtimeRequirePath, channel),
  };
}

module.exports = {
  generate,
  generateServer,
  generateClient,
  buildTypeMap,
};
