/**
 * Pulls the UI tree from Studio (via plugin) and regenerates
 * src/Utils/PlayerUtils/Types.luau
 *
 * Flow (inverse of genRojoTree):
 *   Place (StarterGui) --POST--> localhost --write--> Types.luau
 *
 * Usage:
 *   npm run watch:interfaces   # starts the server (part of npm run dev)
 *   npm run build:interfaces   # starts, waits for 1 sync, then exits (optional)
 *
 * Install plugin once:
 *   npm run install:interface-plugin
 */

const http = require("http");
const fs = require("fs");
const path = require("path");

const PORT = Number(process.env.INTERFACE_TYPES_PORT) || 3847;
const HOST = "127.0.0.1";
const OUT_FILE = path.join(__dirname, "../src/Utils/PlayerUtils/Types.luau");

const BLACKLIST_NAMES = new Set([
  "Cmdr",
  "docks",
  "Freecam",
  "RobloxGui",
  "PlayerList",
  "TopBarApp",
]);

const SKIP_CLASSES = new Set([
  "LocalScript",
  "Script",
  "ModuleScript",
  "PackageLink",
  "Camera",
]);

function isValidIdent(name) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name);
}

function escapeString(value) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function typeKey(name) {
  return isValidIdent(name) ? name : `["${escapeString(name)}"]`;
}

function sanitizeTree(node) {
  if (!node || SKIP_CLASSES.has(node.className) || BLACKLIST_NAMES.has(node.name)) {
    return null;
  }

  const seen = new Set();
  const children = [];
  for (const child of node.children || []) {
    if (seen.has(child.name)) continue;
    const sanitized = sanitizeTree(child);
    if (!sanitized) continue;
    seen.add(child.name);
    children.push(sanitized);
  }

  children.sort((a, b) => a.name.localeCompare(b.name));
  return {
    name: node.name,
    className: node.className,
    children,
  };
}

function renderNode(node, indent) {
  const pad = "\t".repeat(indent);
  if (!node.children || node.children.length === 0) {
    return node.className;
  }

  const lines = [`${node.className} & {`];
  const childPad = "\t".repeat(indent + 1);
  for (const child of node.children) {
    lines.push(`${childPad}${typeKey(child.name)}: ${renderNode(child, indent + 1)},`);
  }
  lines.push(`${pad}}`);
  return lines.join("\n");
}

function collectPaths(node, prefix, paths) {
  const full = prefix ? `${prefix}/${node.name}` : node.name;
  paths.push({
    path: full,
    className: node.className,
    segments: full.split("/"),
    node,
  });
  for (const child of node.children || []) {
    collectPaths(child, full, paths);
  }
}

function generateSource(rootsInput) {
  const roots = [];
  const seenRoots = new Set();

  for (const raw of rootsInput || []) {
    const root = sanitizeTree(raw);
    if (!root) continue;
    if (seenRoots.has(root.name)) continue;
    seenRoots.add(root.name);
    roots.push(root);
  }

  roots.sort((a, b) => a.name.localeCompare(b.name));

  const lines = [
    "--!strict",
    "-- AUTO-GENERATED by tools/genInterfaceTypes.js (npm run dev)",
    "-- Source: StarterGui in the place. Do not edit manually.",
    "",
  ];

  if (roots.length === 0) {
    lines.push("export type Interfaces = {}");
    lines.push("");
    lines.push("export type ByPath = {}");
    lines.push("");
    lines.push("export type InterfacePath = string");
    lines.push("");
    lines.push("return {}");
    lines.push("");
    return lines.join("\n");
  }

  for (const root of roots) {
    lines.push(`export type ${typeKey(root.name)} = ${renderNode(root, 0)}`);
    lines.push("");
  }

  lines.push("export type Interfaces = {");
  for (const root of roots) {
    lines.push(`\t${typeKey(root.name)}: ${typeKey(root.name)},`);
  }
  lines.push("}");
  lines.push("");

  const allPaths = [];
  for (const root of roots) {
    collectPaths(root, "", allPaths);
  }

  // Short alias: first leaf name wins. Luau cannot index type fields (Main.Container invalid),
  // so we expand the node subtree.
  const aliases = [];
  const seenAliasNames = new Set();
  for (const entry of allPaths) {
    const leaf = entry.segments[entry.segments.length - 1];
    if (seenAliasNames.has(leaf)) continue;
    seenAliasNames.add(leaf);
    aliases.push({
      name: leaf,
      className: entry.className,
      node: entry.node,
    });
  }

  const rootNames = new Set(roots.map((r) => r.name));
  for (const alias of aliases) {
    if (rootNames.has(alias.name)) continue;
    if (alias.name === alias.className) continue;
    lines.push(`export type ${typeKey(alias.name)} = ${renderNode(alias.node, 0)}`);
    lines.push("");
  }

  lines.push("export type ByPath = {");
  for (const alias of aliases) {
    let typeExpr;
    if (rootNames.has(alias.name)) {
      typeExpr = typeKey(alias.name);
    } else if (alias.name === alias.className) {
      typeExpr = alias.className;
    } else {
      typeExpr = typeKey(alias.name);
    }
    lines.push(`\t${typeKey(alias.name)}: ${typeExpr},`);
  }
  lines.push("}");
  lines.push("");

  if (allPaths.length === 1) {
    lines.push(`export type InterfacePath = "${escapeString(allPaths[0].path)}"`);
  } else {
    lines.push("export type InterfacePath =");
    for (let i = 0; i < allPaths.length; i++) {
      lines.push(`\t| "${escapeString(allPaths[i].path)}"`);
    }
  }
  lines.push("");
  lines.push("return {}");
  lines.push("");
  return lines.join("\n");
}

function writeTypes(roots) {
  const source = generateSource(roots);
  const previous = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, "utf8") : null;
  if (previous === source) {
    console.log("[genInterfaceTypes] Unchanged.");
    return false;
  }
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, source, "utf8");
  console.log(`[genInterfaceTypes] Wrote ${path.relative(process.cwd(), OUT_FILE)}`);
  return true;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (chunk) => chunks.push(chunk));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

function sendJson(res, status, payload) {
  const body = JSON.stringify(payload);
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  });
  res.end(body);
}

function startServer({ exitAfterSync = false } = {}) {
  let pendingExit = exitAfterSync;

  const server = http.createServer(async (req, res) => {
    if (req.method === "OPTIONS") {
      sendJson(res, 204, {});
      return;
    }

    if (req.method === "GET" && (req.url === "/" || req.url === "/health")) {
      sendJson(res, 200, { ok: true, service: "genInterfaceTypes", port: PORT });
      return;
    }

    if (req.method === "POST" && (req.url === "/sync" || req.url === "/")) {
      try {
        const raw = await readBody(req);
        const payload = JSON.parse(raw || "{}");
        const roots = Array.isArray(payload) ? payload : payload.roots || payload.tree || [];
        writeTypes(roots);
        sendJson(res, 200, { ok: true });
        if (pendingExit) {
          pendingExit = false;
          server.close(() => process.exit(0));
        }
      } catch (error) {
        console.error("[genInterfaceTypes] Sync failed:", error.message);
        sendJson(res, 400, { ok: false, error: error.message });
      }
      return;
    }

    sendJson(res, 404, { ok: false, error: "not found" });
  });

  server.listen(PORT, HOST, () => {
    console.log(`[genInterfaceTypes] Listening on http://${HOST}:${PORT}`);
    console.log("[genInterfaceTypes] Waiting for Studio plugin sync (StarterGui → Types.luau)...");
  });
}

if (require.main === module) {
  const exitAfterSync = process.argv.includes("--once");
  startServer({ exitAfterSync });
}

module.exports = {
  generateSource,
  writeTypes,
  sanitizeTree,
};
